---
# we use docker as plateform
driver:
  name: docker
  privileged: true
  volume: /sys/fs/cgroup:/sys/fs/cgroup
  provision_command:
    - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config

# Ansible will be our provisioner
provisioner:
  name: ansible_playbook
  hosts: localhost
  require_chef_for_busser: false
  require_ruby_for_busser: false
  require_ansible_omnibus: false
  idempotency_test: true

# We use Inspec as testing framework
verifier:
  name: inspec
  inspec_tests:
    - path: tests/inspec

platforms:
  # CentOS
  - name: centos-7-ansible
    driver:
      image: diodonfrost/centos-7-ansible
      platform: centos

  - name: centos-6-ansible
    driver:
      image: diodonfrost/centos-6-ansible
      platform: centos

  # Fedora
  - name: fedora-28-ansible
    driver:
      image: diodonfrost/fedora-28-ansible
      platform: centos
  - name: fedora-27-ansible
    driver:
      image: diodonfrost/fedora-27-ansible
      platform: centos
  - name: fedora-26-ansible
    driver:
      image: diodonfrost/fedora-26-ansible
      platform: centos

  # Ubuntu
  - name: ubuntu-18.04-ansible
    driver:
      image: diodonfrost/ubuntu-18.04-ansible
      platform: ubuntu
  - name: ubuntu-17.10-ansible
    driver:
      image: diodonfrost/ubuntu-17.10-ansible
      platform: ubuntu
  - name: ubuntu-16.04-ansible
    driver:
      image: diodonfrost/ubuntu-16.04-ansible
      platform: ubuntu
  - name: ubuntu-14.04-ansible
    driver:
      image: diodonfrost/ubuntu-14.04-ansible
      platform: ubuntu

  # Debian
  - name: debian-10-ansible
    driver:
      image: diodonfrost/debian-10-ansible
      platform: debian
  - name: debian-9-ansible
    driver:
      image: diodonfrost/debian-9-ansible
      platform: debian
  - name: debian-8-ansible
    driver:
      image: diodonfrost/debian-8-ansible
      platform: debian

  # Oraclelinux
  - name: oraclelinux-7-ansible
    driver:
      image: diodonfrost/oraclelinux-7-ansible
      platform: centos
  - name: oraclelinux-6-ansible
    driver:
      image: diodonfrost/oraclelinux-6-ansible
      platform: centos

  # Amazon
  - name: amazonlinux-2-ansible
    driver:
      image: diodonfrost/amazonlinux-2-ansible
      platform: centos
  - name: amazonlinux-1-ansible
    driver:
      image: diodonfrost/amazonlinux-1-ansible
      platform: centos

  # Gentoo
  - name: gentoo-stage3-ansible
    driver:
      image: diodonfrost/gentoo-stage3-ansible
      platform: gentoo
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable sshd

# Define playbook
suites:
  - name: default
    provisioner:
      name: ansible_playbook
      playbook: tests/test.yml
