---
# Set strong cipher and crypto params

- name: Use strong cipher with opnessh 6.6
  set_fact:
    openssh_ciphers: '{{ ciphers_openssh_66 }}'
  when: openssh_version.stdout >= '6.6' and not openssh_ciphers

- name: Use strong cipher with openssh 5.3
  set_fact:
    openssh_ciphers: '{{ ciphers_openssh_53 }}'
  when: openssh_version.stdout >= '5.3' and not openssh_ciphers
