---
# tasks file for ansible-role-ssh-hardening

- name: Set OS dependent variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: get openssh-version
  shell: ssh -V 2>&1 | sed -r 's/.*_([0-9]*\.[0-9]).*/\1/g'
  args:
    executable: /bin/sh
  changed_when: false
  register: openssh_version
  check_mode: no

- include_tasks: crypto.yml

- include_tasks: sshd.yml
  when: sshd_hardening == true

- include_tasks: ssh.yml
  when: ssh_hardening == true

- include_tasks: public-keys.yml
  when:
    - openssh_keys == true
    - public_keys != ""
