---
# tasks file for ansible-role-ssh-hardening

- name: Set OS dependent variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install openssh-client
  package:
    name: "{{ ssh_client_package }}"
    state: present
  when: ssh_client == 'true'

- include_tasks: sshd.yml
