---
# params openssh-server

- name: Display openssh version
  shell: ssh -V 2>&1 | sed -r 's/.*_([0-9]*\.[0-9]).*/\1/g'
  args:
    executable: /bin/sh
  changed_when: false
  register: sshd_version
  check_mode: no

- name: set atributes on sshd_config file
  file:
    path: "{{ sshd_config }}"
    owner: "{{ sshd_config_owner }}"
    group: "{{ sshd_config_group }}"
    mode: 0600

- name: set banner
  copy:
    src: issue.net
    dest: "{{ sshd_banner }}"
    owner: root
    group: root

- name: Configfile openssh-server
  template:
    src: sshd_config.j2
    dest: "{{ sshd_config }}"
    owner: root
    group: root

- name: Start sshd service
  service:
    name: "{{ sshd_service }}"
    state: started
    enabled: yes
